Задание 2 «Компоненты».
benetta/junior-course-boilerplate pull request #2
Opened 2019-08-11 11:28 UTC by benetta

Постаралась максимально приблизить результат к макету.

2019-08-11 17:03 UTC, CSSSR-School requested changes
Есть несколько замечаний, которые нужно поправить

2019-08-11 17:03 UTC, CSSSR-School commented on package.json
> +    "@babel/cli": "^7.5.0",
Для чего добавили `babel` и прочие зависимости? По идее все должно работать и без них, так как проект построен на CreateReactApp

2019-08-11 17:03 UTC, CSSSR-School commented on public/index.css
> +.header {
Все стили нужно также разбить на компоненты и положить рядом со своими JS файлами компонентов.

2019-08-11 17:03 UTC, CSSSR-School commented on public/index.css
> +.item-list > div {
Не стоит делать каскад по тегам, тем более на `div`. Это всегда усложняет поддержку кода. Лучше создать какой-то класс и повесить на этот `div`

2019-08-11 17:03 UTC, CSSSR-School commented on src/components/Header.js
> +	return <h1 className='header'>Список товаров</h1>
Попробуйте сделать так, чтобы текст заголовка можно было передавать в компонент динамически. Таким образом, мы сможем его потом переиспользовать

2019-08-11 17:03 UTC, CSSSR-School commented on src/components/ItemList.js
> +			key={item.title}
В качестве значения `key` лучше использовать `id` товара

2019-08-11 17:03 UTC, CSSSR-School commented on src/components/ProductItem.js
> +
Данный компонент можно подключить как зависимость в `package.json`:
```diff
+ "csssr-school-product-card": "git+https://github.com/CSSSR-School/junior-course-product-card.git",
```

И подключить в нужном месте таким образом:
```js
import ProductItem from 'csssr-school-product-card';
```

2019-08-12 12:00 UTC, benetta commented on src/components/ProductItem.js
> +
не знала что так можно. так конечно намного удобнее)

2019-08-12 12:00 UTC, benetta commented on src/components/ItemList.js
> +			key={item.title}
поправила.

2019-08-12 12:01 UTC, benetta commented on src/components/Header.js
> +	return <h1 className='header'>Список товаров</h1>
теперь текст заголовка приходит в пропс.

2019-08-12 12:02 UTC, benetta commented on public/index.css
> +.item-list > div {
Этот вариант был выбран потому, что я не знала как передать класс в компонент карточки, не изменяя его вручную. Сделала черёз обёртку li.

2019-08-12 12:03 UTC, benetta commented on public/index.css
> +.header {
положила каждый компонент в папку со своим стилем.

2019-08-12 12:04 UTC, benetta commented on package.json
> +    "@babel/cli": "^7.5.0",
по идее да, но на всякий случай скопировала их при переносе компонента с карточкой из package.json карточки) Подключила карточку нормально, всё убрала.

2019-08-12 16:54 UTC, CSSSR-School requested changes

2019-08-12 16:54 UTC, CSSSR-School commented on src/components/ItemList/index.js
> +	let items = data.map(item =>
Почему let? Разве дальше есть переприсваивание?

2019-08-12 16:54 UTC, CSSSR-School commented on src/components/Header/index.js
> +	return <h1 className='header'>{props.title}</h1>
Если знаешь, как работает children, то можно сделать более универсальное решение. Если нет, то тогда не делай ничего, далее будет урок об этом.)

2019-08-12 17:16 UTC, benetta commented on src/components/ItemList/index.js
> +	let items = data.map(item =>
не знаю, не люблю const просто) поправила.

2019-08-12 17:17 UTC, benetta commented on src/components/Header/index.js
> +	return <h1 className='header'>{props.title}</h1>
урок про SRP? попробовала с children. не знаю только как лучше, с переменной или без. Через переменную кажется надёжнее.

2019-08-12 18:08 UTC, CSSSR-School commented on src/components/Header/index.js
> +	return <h1 className='header'>{props.title}</h1>
А что, если в Header не только текст может прийти?
Например:
```
<Header>
</Header>

2019-08-12 18:10 UTC, CSSSR-School commented on src/components/Header/index.js
> +	return <h1 className='header'>{props.title}</h1>
Через children мы получаем более универсальный компонент, который может любых потомков принимать)

2019-08-12 18:10 UTC, CSSSR-School commented on src/components/ItemList/index.js
> +	let items = data.map(item =>
Это до первого настроенного линтера или CI/CD)))

2019-08-12 18:17 UTC, benetta commented on src/components/Header/index.js
> +	return <h1 className='header'>{props.title}</h1>
этот момент вроде понятен)

2019-08-12 18:17 UTC, merged